apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:  replicast-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx-pods-label
  template:
    metadata:
      name:  my-nginx-pod
      labels:
        app: my-nginx-pods-label
    spec:
      containers:
        - image:  nginx:latest
          name:  nginx
          ports:
          - containerPort: 80 