apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
  labels:
    name: emptydir-pod
spec:
  containers:
  - name: content-creator
    image: alicek106/alpine-wget:latest
    args: ["tail", "-f", "/dev/null"]
    volumeMounts:
      - mountPath: /data                        # 해당 컨테이너가 /data 에 파일을 생성하면
        name: my-emptydir-volume

  - name: apache-webserver
    image: httpd:2
    args: ["tail", "-f", "/dev/null"]
    volumeMounts:
      - mountPath: /usr/local/apache2/htdocs/   # 아파치 웹 서버에서 접근할 수 있음
        name: my-emptydir-volume
        
  volumes:
    - name: my-emptydir-volume
      emptyDir: {}                              # 포드 내에서 파일을 공유하는 emptydDir