apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  selector:
    role: nfs-server
  ports:
  - port: 2049
    name:  nfs
  - port: 20048
    name:  mountd
  - port: 111
    name:  rpcbind
