apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
  - name: nfs-mount-container
    image: busybox
    args: ["tail", "-f", "/dev/null"]
    volumeMounts:
      - mountPath: /mnt                 # 포드 컨테이너 내부의 /mnt 디렉터리에 마운트
        name: nfs-volume
  volumes:
    - name: nfs-volume
      nfs:                              # NFS 서버의 볼륨을 포드의 컨테이너에 마운트
        path: /
        server: 10.105.173.246