#spring:
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    enabled: true
#    sleuth:
#      sampler:
#        probability: 1.0
#  application:
#    name: Demo Sleuth Tutorial
#logging:
#  level:
#    root: DEBUG