apiVersion: v1
kind: Pod
metadata:
  name: container-env-example
spec:
  containers:
  - name: my-container
    image: busybox
    args: ['tail', '-f', '/dev/null']
    envFrom:
      - configMapRef:
          name: log-level-configmap
      - configMapRef:
          name: start-k8s
