apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: my-webserver
        image: alicek106/rr-test:echo-hostname
        ports:
        - containerPort: 80


--- 

apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-nodeport
  namespace: production
spec:
  selector:
    app: webserver
  ports:
  - port: 8080
    targetPort: 80
    name: web-port
  type: NodePort