apiVersion: v1
kind: Pod
metadata:
  name: selective-cm-volume-pod
spec:
  containers:
  - name: my-container
    image: busybox
    args: ['tail', '-f', '/dev/null']
    volumeMounts:
      - mountPath: /etc/config    # 마운트 위치는 변경되지 않음
        name: configmap-volume
  volumes:
    - name: configmap-volume
      configMap:
        name: start-k8s
        items:                    # 컨피그맵에서 가졍로 키-값의 목록을 나열
          - key: k8s              # k8x라는 키에 대응하는 값을 가져옴
            path: k8s_fullname    # 최종 파일 이름은  k8s_fullname