apiVersion: v1
kind: Pod
metadata:
  name: container-selective-env-example
spec:
  containers:
  - name: my-container
    image: busybox
    args: ['tail', '-f', '/dev/null']
    env:
      - name: ENV_KEYNAME_1 # 컨테이너에 새롭게 등록될 환경 변수 이름
        valueFrom:
          configMapKeyRef:
            key: LOG_LEVEL
            name: log-level-configmap
      - name: ENV_KEYNAME_2 # 컨테이너에 새롭게 등록될 환경 변수 이름
        valueFrom:
          configMapKeyRef:
            key: k8s # 가져올 데이터 값의키
            name: start-k8s # 참조할 컨피그맵의 이름
