apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - name: my-container
    image: busybox
    args: ['tail', '-f', '/dev/null']
    volumeMounts:                         
      - mountPath: /etc/secret            # 시크릿의 데이터가 위취할 경로
        name: secret-volume               # volumes에서 정의한 시크릿 볼륨 이름
  volumes:
    - name: secret-volume                 # 시크릿 볼륨 이용
      secret:
        secretName: our-password                # 키-값 쌍을 가져올 시크릿 이름