server:
  port: 9000

spring:
  cloud:
    gateway:
      default-filters:
        - name: AuthFilter
          args:
            whiteList:
              passToken: admin

      routes:
        - id: all
          uri: http://localhost:8080
          predicates:
            - Path=/**
          filters:
            - name: RequestRateLimitFilter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                redis-rate-limiter.requestedTokens: 1
                #                redis-rate-limiter.replenishRate: 20
                #                redis-rate-limiter.burstCapacity: 100
                #                redis-rate-limiter.requestedTokens: 3
                key-resolver: "#{@userIdAsKeyResolver}"

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
